log_pattern = r'^([\d.]+) - - \[(.*?)\] "(.*?)" (\d+) (\d+)$'
log_file = 'access_logs.txt'
resolution = '1280x720+200+100'
database = 'access_log'
user = 'postgres'
password = 'root'
host = 'localhost'
port = '5432'
timeschedule = 30
power_shell_script_path = r"C:\Users\zxceb\PycharmProjects\UchebPrac\reload_logs.ps1"
script_path = r"C:\Users\zxceb\PycharmProjects\UchebPrac\schedulescript.py"
script_file = "reload_logs.ps1"
task_name = "Parse logs"
trigger_time = "0:00"