log_pattern = r'^([\d.]+) - - \[(.*?)\] "(.*?)" (\d+) (\d+)$'
log_file = 'access_logs.txt'
resolution = '1280x720+200+100'
database = 'access_log'
user = 'postgres'
password = 'root'
host = 'localhost'
port = '5432'